import "./globals.css";

export const metadata = {
  title: "FaceTracking app",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="matrix-container">
        <div className="matrix-grid">{children}</div>
      </body>
    </html>
  );
}
